services:
  # Redis for Celery message broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # FastAPI application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery worker
  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./temp:/app/temp
      - ../wrappers:/app/wrappers
      - ../models:/app/models
    restart: unless-stopped
    command: celery -A worker.celery_app worker --loglevel=info --concurrency=1

volumes:
  redis_data:
